swagger: '2.0'
info:
  version: 1.0.0
  title: AWS Lambda Starter
host: example.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Random string
      operationId: hello
      responses:
        '200':
          description: Returns a random string
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
